version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cockroach-backend
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - game-network

  frontend:
    build: ./frontend
    container_name: cockroach-frontend
    ports:
      - "3000:80"
    networks:
      - game-network

  db:
    image: postgres:15
    container_name: cockroach-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - game-network

  redis:
    image: redis:7
    container_name: cockroach-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - game-network

  nginx:
    image: nginx:alpine
    container_name: cockroach-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    depends_on:
      - backend
      - frontend
    networks:
      - game-network

volumes:
  postgres-data:
  redis-data:

networks:
  game-network:
    driver: bridge